<a href="https://colab.research.google.com/github/jorgecaraveobalderas-beep/Class-Files/blob/main/S06_Actividad_02_ALGEBRALINEAL_274702.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Actividad calificada — Álgebra lineal con NumPy

**Programación para Analítica Descriptiva y Predictiva**
Maestría en Inteligencia Artificial y Analítica de Datos — UACJ

---

**Material de estudio previo:** `Material_Extra_Algebra_Lineal_NumPy.ipynb`. Revísalo antes de resolver esta actividad.

**Entrega:** individual, en este notebook de Google Colab (comparte el enlace con permiso de edición para el docente).
**Plazo:** 7 días naturales a partir de la publicación de esta actividad.
**Penalización por entrega tardía:** 5% por día, hasta 7 días; después de eso, la actividad no se recibe.
**Valor total:** 100 puntos.

### Herramientas permitidas

Esta actividad evalúa `np.linalg.norm()`, `np.dot()`/`@`, `np.linalg.det()`, `np.linalg.inv()`, `np.linalg.solve()`, y las operaciones de NumPy ya vistas en sesiones anteriores. No uses pandas ni scikit-learn.

### Cómo se evalúa

Cada ejercicio indica su valor en puntos. Se evalúa el resultado correcto **y** el uso de la función específica de `np.linalg` indicada en cada enunciado — calcular a mano una fórmula que NumPy ya resuelve (por ejemplo, programar la fórmula del determinante 2×2 en vez de usar `np.linalg.det()`) no obtiene el puntaje completo.

In [ ]:
import numpy as np

## Parte 1 — Vectores: perfiles de producto

Una tienda en línea representa cada producto como un vector de 3 componentes: calificación de calidad, calificación de precio, y calificación de servicio (escala 1 a 5, donde 5 es mejor). Ejecuta la siguiente celda para cargar los tres productos — **no la modifiques**.

In [ ]:
producto_A = np.array([4.5, 3.2, 5.0])
producto_B = np.array([4.0, 2.8, 4.7])
producto_C = np.array([1.0, 5.0, 1.2])

print(producto_A, producto_B, producto_C)

[4.5 3.2 5. ] [4.  2.8 4.7] [1.  5.  1.2]


---

### Ejercicio 1 — Norma de los vectores (10 pts)

Calcula la norma de `producto_A`, `producto_B` y `producto_C` usando `np.linalg.norm()`.

In [ ]:
# Tu código aquí

norma_A = np.linalg.norm(producto_A)
norma_B = np.linalg.norm(producto_B)
norma_C = np.linalg.norm(producto_C)

print(norma_A, norma_B, norma_C)



7.449161026585477 6.777167549942971 5.238320341483518


---

### Ejercicio 2 — Producto punto y ángulo (15 pts)

1. Calcula el producto punto entre `producto_A` y `producto_B`, y entre `producto_A` y `producto_C`, usando `np.dot()` o `@`.
2. Calcula el ángulo (en grados) entre `producto_A` y `producto_B`, y entre `producto_A` y `producto_C`.
3. Con base en los ángulos obtenidos, indica (en un comentario o celda de texto) cuál de los dos productos (`B` o `C`) es más similar a `producto_A`, y por qué el ángulo es el indicador correcto para esa comparación.

In [ ]:
# Tu código aquí


# 1.-

producto_punto_AB = np.dot(producto_A, producto_B)
print(producto_punto_AB)
producto_punto_AC = np.dot(producto_A, producto_C)
print(producto_punto_AC)

# 2.-

calculo_angulo_AB_radianes = np.arccos(producto_punto_AB / (norma_A * norma_B))
print(calculo_angulo_AB_radianes)
calculo_angulo_AB_grados = np.degrees(calculo_angulo_AB_radianes)
print(calculo_angulo_AB_grados)

calculo_angulo_AC_radianes = np.arccos(producto_punto_AC / (norma_A * norma_C))
print(calculo_angulo_AC_radianes)
calculo_angulo_AC_grados = np.degrees(calculo_angulo_AC_radianes)
print(calculo_angulo_AC_grados)

#3.-

# Dado que el angulo entre AB es 1.77, mientras que AC es 47.22, quiere decir que el producto B es mas similar a producto A, debido a que el angulo de estos es mas cercano a 0, con respecto a C,
# por lo que estos vectores (AB) tienen una direccion similar en el espacio vectorial



50.46
26.5
0.0309722914852852
1.7745815839558179
0.8242333568711709
47.22509268261831


---

### Ejercicio 3 — Normalización (10 pts)

Normaliza los tres vectores (`producto_A`, `producto_B`, `producto_C`) para obtener sus vectores unitarios. Verifica, imprimiendo el resultado, que la norma de cada vector normalizado sea 1.

In [ ]:
# Tu código aquí

A_unitario = producto_A / np.linalg.norm(producto_A)
print(A_unitario)
B_unitario = producto_B / np.linalg.norm(producto_B)
print(B_unitario)
C_unitario = producto_C / np.linalg.norm(producto_C)
print(C_unitario)

print(np.linalg.norm(A_unitario))
print(np.linalg.norm(B_unitario))
print(np.linalg.norm(C_unitario))


[0.60409488 0.42957858 0.67121653]
[0.59021707 0.41315195 0.69350506]
[0.19090089 0.95450444 0.22908106]
1.0
1.0
1.0


## Parte 2 — Matrices: mezcla de insumos

Una fábrica de jugos combina dos insumos (concentrado de fruta y agua) en distintas proporciones para dos líneas de producto. La matriz `M` representa esas proporciones (filas = línea de producto, columnas = insumo), y `P` representa un ajuste de escala para una nueva presentación. Ejecuta la siguiente celda — **no la modifiques**.

In [ ]:
M = np.array([[2, 1],
              [1, 3]])

P = np.array([[1.5, 0],
              [0, 2.0]])

print(M)
print(P)

[[2 1]
 [1 3]]
[[1.5 0. ]
 [0.  2. ]]


---

### Ejercicio 4 — Multiplicación matricial (15 pts)

1. Calcula `M * P` (elemento a elemento) y `M @ P` (multiplicación matricial). Los resultados son distintos — en un comentario o celda de texto, explica brevemente por qué.
2. Verifica que las formas sean compatibles: ¿cuál sería el resultado de `P @ M`? Calcúlalo y compáralo con `M @ P` — ¿da el mismo resultado?

In [ ]:
# Tu código aquí

# 1.-

print("Elemento a elemento (*):")
print(M * P)

print("Multiplicación matricial (@):")
print((M @ P),"\n\n\n")

#Son diferentes porque en elemento a elemento, multiplica cada posicion de la primera matriz por la misma posicion de la segunda matriz, mientas que el la multiplicacion matricial es la suma del
# producto punto de ambas matrices

# 2.-

print("Multiplicación matricial (@):")
print(P @ M)

# No da el mismo resultado porque la matriz matricial no es conmutativa


Elemento a elemento (*):
[[3. 0.]
 [0. 6.]]
Multiplicación matricial (@):
[[3.  2. ]
 [1.5 6. ]] 



Multiplicación matricial (@):
[[3.  1.5]
 [2.  6. ]]


---

### Ejercicio 5 — Determinante e inversa (15 pts)

1. Calcula el determinante de `M` con `np.linalg.det()`. Confirma que `M` sí tiene inversa (determinante distinto de 0).
2. Calcula la inversa de `M` con `np.linalg.inv()`.
3. Verifica tu resultado calculando `M @ M_inv` — debe dar (aproximadamente) la matriz identidad.

In [ ]:
# Tu código aquí


# 1.-

determinante_M = np.linalg.det(M)
print("M si tiene inversa, debido a que la determinante de M es distinta a 0, siendo que el valor es", determinante_M)


# 2.-

M_inversa = np.linalg.inv(M)
print(M_inversa)

# 3.-

# Verificación: M @ M_inversa debe dar (aproximadamente) la matriz identidad

M_por_M_inversa = M @ M_inversa
print(M_por_M_inversa)



M si tiene inversa, debido a que la determinante de M es distinta a 0, siendo que el valor es 5.000000000000001
[[ 0.6 -0.2]
 [-0.2  0.4]]
[[ 1.00000000e+00  0.00000000e+00]
 [-5.55111512e-17  1.00000000e+00]]


---

### Ejercicio 6 — Sistema de ecuaciones (15 pts)

La fábrica necesita producir un lote que requiere en total 180 unidades de la línea 1 y 300 unidades de la línea 2, según las proporciones de `M`. Esto se representa como el sistema $Mx = b$, con:

```python
b = np.array([180, 300])
```

1. Resuelve el sistema con `np.linalg.solve()` para encontrar cuántas unidades de cada insumo (`x`) se necesitan.
2. Verifica tu solución multiplicando `M @ x` y confirmando que el resultado coincide con `b`.

In [ ]:
b = np.array([180, 300])
M = np.array([[2, 1],
              [1, 3]])
# 1.-

solucion = np.linalg.solve(M, b)
print(solucion)

# 2.-

M_por_solucion = M @ solucion
print(M_por_solucion)



[48. 84.]
[180. 300.]


---

### Ejercicio 7 — Síntesis: distancia y similitud (20 pts)

Retomando los tres productos de la Parte 1:

1. Calcula la **distancia euclidiana** entre `producto_A` y `producto_B`, y entre `producto_A` y `producto_C`, usando la norma de la diferencia entre los vectores (`np.linalg.norm(a - b)`).
2. Calcula la **similitud coseno** entre los mismos pares — es el cociente que ya calculaste en el Ejercicio 2 antes de aplicar `arccos()`: $\frac{a \cdot b}{\|a\| \|b\|}$.
3. Con base en ambas métricas (distancia y similitud coseno), concluye en una cadena de texto impresa cuál producto (`B` o `C`) es más parecido a `producto_A`, y si ambas métricas coinciden en la misma conclusión.

In [ ]:
# 1.-

distancia_A_B = np.linalg.norm(producto_A - producto_B)
print(distancia_A_B)
distancia_A_C = np.linalg.norm(producto_A - producto_C)
print(distancia_A_C)

# 2.-
similitud_coseno_A_B = np.dot(producto_A, producto_B) / (np.linalg.norm(producto_A) * np.linalg.norm(producto_B))
print(similitud_coseno_A_B)
similitud_coseno_A_C = np.dot(producto_A, producto_C) / (np.linalg.norm(producto_A) * np.linalg.norm(producto_C))
print(similitud_coseno_A_C)

# 3.-

distancia_es = "B" if distancia_A_B < distancia_A_C else "C"
similitud_es = "B" if similitud_coseno_A_B > similitud_coseno_A_C else "C"

print(f"En base a distancia, el mas parecido a producot A es {distancia_es}")
print(f"En base a similitud coseno, el mas parecido a producto es {similitud_es}")

if distancia_es == similitud_es:
  print("Ambas metricas coinciden")
else:
  print("Ambas metricas no coinciden")



0.7071067811865476
5.470831746635972
0.9995203969214979
0.6791199021706347
En base a distancia, el mas parecido a producot A es B
En base a similitud coseno, el mas parecido a producto es B
Ambas metricas coinciden


---

## Antes de entregar

- Verifica que el notebook completo corra de principio a fin sin errores (**Entorno de ejecución → Ejecutar todas**).
- Confirma que no usaste pandas ni scikit-learn.
- Comparte el notebook con permiso de **edición** para el docente.